---
extends: default

ignore: |
  node_modules/

rules:
  line-length:
    ignore: |
      /.github/workflows/*.yaml
      /.github/workflows/*.yml
      /.github/settings.yml
      /*-lock.yaml
  truthy:
    ignore: |
      /.github/workflows/*.yaml
      /.github/workflows/*.yml
